### ISSUE TITLE
Numbering episodes within a CIS

### ISSUE THREAD

**Issue by catherineperkins** [Public-Health-Scotland/phsmethods#32]
We discussed in the QI R toolkit meetings that it would be useful to have a function which creates episode numbers within a CIS as this is something we do a lot with the QI team for information requests. We also thought that perhaps part of this could include being able to select the first/last episode in a CIS which we are sometimes required to do. The plan is for me to take this forward working very closely with @davidc92  
 
Would be good to hear your thoughts.

**Comment by jackhannah95** [comment]
Yeah sounds good 👍 We're going to do a 0.2.0 release of the package next week, and a lot of the documentation and whatnot will likely be updated for that. Might be worth holding off until after that so that nothing's out of date on your branch but, aside from that, go for it.

**Comment by catherineperkins** [comment]
Thanks for reviewing, Jack. It's very early days so it's no problem to hold off until the package is updated.

**Comment by catherineperkins** [comment]
Nick Christofidis has advised that code is available here that contains a function to do this: https://phs-git.nhsnss.scot.nhs.uk/Nic-Chr/rtemethods/src/branch/master/R/add_episodes.R
Contact Nick for further info :-)
