### ISSUE TITLE
file_size masks function from fs

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phsmethods#46]
`file_size` is masking `file_size` from [fs](https://fs.r-lib.org/). fs is not core tidyverse but is included so would be ideal if it wasn't masked.

I think the simplest solution would be to just rename the function when dealing with issue #11.

**Comment by davidc92** [comment]
I don't think this is that big a deal - different packages having functions of the same name is pretty unavoidable. I don't think it's worth the effort bending over backwards trying to ensure that our function names are 100% unique, particularly to avoid masking something so obscure. Of course this would be different if we were masking something like `mutate`, but I'm content to just leave this as is. People can use `::` if they really need to use both in the same script.
