### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by peterhall001** [Public-Health-Scotland/phsmethods#49]
This would be invaluable to those working in the National Research Safe Haven

**Comment by Moohan** [comment]
Not that I'm against this idea in principal but is it not possible for it to be installed in the Safe Haven already, either from GitHub or from source?

**Comment by davidc92** [comment]
Hi Peter

This is something that we will be looking into in the coming months, but I'm not going to hold my breath. CRAN standards are very strict and I'm not sure this package would be viewed as useful enough to make the cut. Although will leave this issue open so I can give an update if/when we submit it. 

D

**Comment by peterhall001** [comment]
Thanks David!

**Comment by Moohan** [comment]
I've recently had a package I developed accepted to CRAN and it really wasn't as bad as I was expecting! I'd be happy to lead on this / advise.

**Comment by peterhall001** [comment]
Wonderful! Thank you.
P

**Comment by Moohan** [comment]
Just adding for reference - [https://cran.r-project.org/web/packages/phsmethods/index.html]()

**Comment by davidc92** [comment]
Popping in to say this is great :) Well done all!

> Just adding for reference - https://cran.r-project.org/web/packages/phsmethods/index.html
