### ISSUE TITLE
Data profiling

### ISSUE THREAD

**Issue by davidc92** [Public-Health-Scotland/phsmethods#51]
A function to carry out data profiling as typically required by data management. What I mean by that is: 

- A summary of the completeness/missingness of each variable in a dataset
- If a variable is a date, what is the range?
- If variable is a factor, frequencies of each factor level

I strongly suspect this ask may be fulfilled by another package, but if not I don't think this should be too tricky a function to write.

**Comment by jvillacampa** [comment]
As you say there are a couple of packages out there for this purpose. See this one:
https://towardsdatascience.com/simple-fast-exploratory-data-analysis-in-r-with-dataexplorer-package-e055348d9619
And functions to do this type of jobs in different packages:
https://www.r-bloggers.com/2018/08/exploratory-data-analysis-in-r-introduction/
Things like your second and third points can be done in base R (range(df$date); table(df$factor)

There might specific jobs for which developing a new function is required, but perhaps, it's more a matter of having a guide on how to do this type of stuff?

**Comment by alicebyers5** [comment]
This function might be similar to what you're after too - https://github.com/jackhannah95/jafun/blob/master/R/prop_missing.R
