### ISSUE TITLE
Function to replace NaN values.

### ISSUE THREAD

**Issue by Nic-Chr** [Public-Health-Scotland/phsmethods#64]
Simple function to replace NaN values, similarly named to `tidyr::replace_na()`.
```R
replace_nan <- function(x, value){
  x[is.nan(x)] <- value
  x
}
```

**Comment by Moohan** [comment]
I suggested this at https://github.com/tidyverse/tidyr/issues/1149 and it was rejected as too specific for tidyr. I'm not sure I've ever come across `NaN` data so I wouldn't have a use for it but I'm assuming at least @Nic-Chr has in the past so the function would be useful!
