### ISSUE TITLE
Turn the 'using phsmethods' section in the readme into a series of vignettes 

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phsmethods#82]
Th 'using phsmethods' section on the readme is very long, but at the same time, we could go into more detail on the usage of some of the functions (optional params, usage in a data pipeline context etc.).

I think the section could be trimmed to a single paragraph and with a list of links to vignettes/articles on each function/set of functions.

This would hopefully make it all more digestible and easy to use for new users. I think a lot of the content is already there so it would mostly be a case of refactoring it all in the first instance, and then adding to it once we're happy with the structure.

**Comment by Tina815** [comment]
I have added some paragraphs directing users to pkgdown website and the online training course. Now the section is much shorter and less maintenance.
